client:
	gcc -o client TCP_Client/client.c TCP_Client/clientHandler.c TCP_Client/clientHandler.h
server:
	gcc -o server TCP_Server/server.c TCP_Server/serverHandler.c TCP_Server/serverHandler.h
clean:
	rm -f $(TARGET)